# image: homolo/node-angular:8

# cache:
#   untracked: true
#   paths:
#     - node_modules/

# stages:
#   - deploy-master

# deploy-master:
#   stage: deploy-master
#   only:
#     - master
#   script: 
#     - echo "发布人民调解云学院正式环境前端代码"
#     - ls -l
#     - cp proxy.config.js.sample proxy.config.js
#     # - rm -rf node_modules
#     - npm config set registry https://registry.npm.taobao.org
#     - npm config set chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver
#     - npm config set sass-binary-site http://npm.taobao.org/mirrors/node-sass
#     - npm config set phantomjs_cdnurl=http://cnpmjs.org/downloads
#     - npm install
#     - npm run build
#     - tar cjf mediation-cloud-academy-mobile.tar.bz2 dist
#     - ls -l
#     - scp mediation-cloud-academy-mobile.tar.bz2 s10:/home/docker/deploy/
#     - ssh s10 "/apps/deploy-front-end.sh mediation-learn"
#     - rm -r mediation-cloud-academy-mobile*
#     - ls -l